//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int Id { get; set; }
        public int FacultadId { get; set; }
        public string Descripcion { get; set; }
        public bool Bonificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Estado { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string DNI { get; set; }
    
        public virtual Facultad Facultad { get; set; }
        public virtual User User { get; set; }
    }
}
